name: Build and update caches
on:
  pull_request:
    branches:
      - master
    types: [closed]

permissions:
  # Needed to avoid "Unable to reserve cache" issues for bazel jobs.
  actions: write

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/build.yml
    with:
      run-tests: false
      update-caches: true
